# Generated by Django 3.1.12 on 2025-04-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('queue_data', models.BinaryField()),
                ('version', models.IntegerField(default=0)),
            ],
        ),
    ]
